In [48]:
%load_ext autoreload
%autoreload
%matplotlib inline
import rasterio
import sys
sys.path.insert(0, "..")
import src.satellite_analyze
import src.locate_trees
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [49]:
tifffile = '/app/data/raw/athens_satellite.tif'
sat_data = rasterio.open(tifffile)

In [50]:
tree_dict, tree_loc = src.locate_trees.pred_tiff(tifffile, r_start=10000, r_end=12000, c_start=10000, c_end=12000)

sat file (43589x43757)
Number of origins 100
Percent done: 0.05
Percent done: 0.1
Percent done: 0.15
Percent done: 0.2
Percent done: 0.25
Percent done: 0.3
Percent done: 0.35
Percent done: 0.4
Percent done: 0.45
Percent done: 0.5
Percent done: 0.55
Percent done: 0.6
Percent done: 0.65
Percent done: 0.7
Percent done: 0.75
Percent done: 0.8
Percent done: 0.85
Percent done: 0.9
Percent done: 0.95
Percent done: 1.0


In [51]:
tree_dict[98]

{'origin': (11894, 11678),
 'size': [200, 200],
 'local': array([[0.72942756, 0.29961045, 0.99045681, 0.01259218, 0.41242903],
        [0.30644168, 0.70897839, 0.2801251 , 0.82767238, 0.2379342 ],
        [0.5101982 , 0.51232098, 0.10488469, 0.14236666, 0.70948133]]),
 'global': array([[1.20398855e+04, 1.17379221e+04, 1.98091362e+02, 2.51843513e+00,
         1.00000000e+00],
        [1.19552883e+04, 1.18197957e+04, 5.60250192e+01, 1.65534476e+02,
         1.00000000e+00],
        [1.19960396e+04, 1.17804642e+04, 2.09769389e+01, 2.84733329e+01,
         1.00000000e+00]])}

In [ ]:
org_r, org_c = src.locate_trees.divide_tiff(sat_data, image_w=200, image_h=200)

In [25]:
a = np.random.rand(4,3)
print(a)
a[:, 0] += 10
print(a)
a[:, 0] = a[:, 0] + 1000
print(a)

[[0.87525958 0.75920774 0.67194009]
 [0.81583707 0.1692085  0.46560353]
 [0.14927874 0.26208891 0.42909141]
 [0.30098211 0.87330275 0.24869645]]
[[10.87525958  0.75920774  0.67194009]
 [10.81583707  0.1692085   0.46560353]
 [10.14927874  0.26208891  0.42909141]
 [10.30098211  0.87330275  0.24869645]]
[[1.01087526e+03 7.59207737e-01 6.71940092e-01]
 [1.01081584e+03 1.69208504e-01 4.65603531e-01]
 [1.01014928e+03 2.62088909e-01 4.29091412e-01]
 [1.01030098e+03 8.73302749e-01 2.48696454e-01]]


In [29]:
b = np.empty((0,3), int)
b = np.append(b, a, axis=0)
print(b)
b = np.append(b, a, axis=0)
print(b)

[[1.01087526e+03 7.59207737e-01 6.71940092e-01]
 [1.01081584e+03 1.69208504e-01 4.65603531e-01]
 [1.01014928e+03 2.62088909e-01 4.29091412e-01]
 [1.01030098e+03 8.73302749e-01 2.48696454e-01]]
[[1.01087526e+03 7.59207737e-01 6.71940092e-01]
 [1.01081584e+03 1.69208504e-01 4.65603531e-01]
 [1.01014928e+03 2.62088909e-01 4.29091412e-01]
 [1.01030098e+03 8.73302749e-01 2.48696454e-01]
 [1.01087526e+03 7.59207737e-01 6.71940092e-01]
 [1.01081584e+03 1.69208504e-01 4.65603531e-01]
 [1.01014928e+03 2.62088909e-01 4.29091412e-01]
 [1.01030098e+03 8.73302749e-01 2.48696454e-01]]


In [16]:
np.random.randint(1)

0

In [27]:
print(org_r)
print(org_c)

[   78.   278.   478.   678.   878.  1078.  1278.  1478.  1678.  1878.
  2078.  2278.  2478.  2678.  2878.  3078.  3278.  3478.  3678.  3878.
  4078.  4278.  4478.  4678.  4878.  5078.  5278.  5478.  5678.  5878.
  6078.  6278.  6478.  6678.  6878.  7078.  7278.  7478.  7678.  7878.
  8078.  8278.  8478.  8678.  8878.  9078.  9278.  9478.  9678.  9878.
 10078. 10278. 10478. 10678. 10878. 11078. 11278. 11478. 11678. 11878.
 12078. 12278. 12478. 12678. 12878. 13078. 13278. 13478. 13678. 13878.
 14078. 14278. 14478. 14678. 14878. 15078. 15278. 15478. 15678. 15878.
 16078. 16278. 16478. 16678. 16878. 17078. 17278. 17478. 17678. 17878.
 18078. 18278. 18478. 18678. 18878. 19078. 19278. 19478. 19678. 19878.
 20078. 20278. 20478. 20678. 20878. 21078. 21278. 21478. 21678. 21878.
 22078. 22278. 22478. 22678. 22878. 23078. 23278. 23478. 23678. 23878.
 24078. 24278. 24478. 24678. 24878. 25078. 25278. 25478. 25678. 25878.
 26078. 26278. 26478. 26678. 26878. 27078. 27278. 27478. 27678. 27878.
 28078

In [133]:
if None:
    print('hello')

In [32]:
num_runs = len(org_r) * len(org_c)
print(num_runs)

47524


In [35]:
np.min([45, np.inf]).astype('int')

45

In [37]:
rows = np.array([1,2,3])
columns = np.array([4,5,6,7,8])
c2, r2 = np.meshgrid(columns, rows)

In [63]:
origin = [(r,c) for r in rows for c in columns]
print(origin)

[(1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8)]


In [39]:
print(c2) 
print(r2)

[[4 5 6 7 8]
 [4 5 6 7 8]
 [4 5 6 7 8]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


In [61]:
out = np.dstack((r2,c2))
print(out.shape)

(3, 5, 2)


In [52]:
out_ravel = out.ravel()

In [59]:
out_ravel[1]

4

In [8]:
if 1 is not None:
    print('hello')

hello
