In [202]:
%load_ext autoreload
%autoreload
%matplotlib inline
# import rasterio
import sys
import numpy as np
sys.path.insert(0, "..")
import src.models.predict_classes

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [203]:
tif_path = '../data/raw/athens_satellite.tif'
rel_path = '../data/processed/athens'
r_start=1000
r_end=2000
c_start=1000
c_end=2000
sat_master = src.models.predict_classes.SatelliteTif(tif_path, rel_path,
                 c_channels=[0, 1, 3], sub_img_w=200, sub_img_h=200,
                 num_train = 20, valid_frac = 0.3,
                 r_start=1000, r_end=2000, c_start=c_start, c_end=c_end)

In [204]:
len(sat_master.pred_origins)

25

In [205]:
sat_master.pred_origins

array([[1000, 1000],
       [1000, 1200],
       [1000, 1400],
       [1000, 1600],
       [1000, 1800],
       [1200, 1000],
       [1200, 1200],
       [1200, 1400],
       [1200, 1600],
       [1200, 1800],
       [1400, 1000],
       [1400, 1200],
       [1400, 1400],
       [1400, 1600],
       [1400, 1800],
       [1600, 1000],
       [1600, 1200],
       [1600, 1400],
       [1600, 1600],
       [1600, 1800],
       [1800, 1000],
       [1800, 1200],
       [1800, 1400],
       [1800, 1600],
       [1800, 1800]])

In [206]:
sat_master.build_train_dataset()
print('built train')
sat_master.build_valid_dataset()
print('built valid')
sat_master.build_pred_dataset()
print('built pred')

built train
built valid
built pred


In [193]:
sat_master.clean_pred_images()
sat_master.clean_train_images()
sat_master.clean_valid_images()

In [170]:
print(len(sat_master.pred_origins))
print(sat_master.pred_origins)

1308
[[  872     0]
 [  872   200]
 [  872   400]
 ...
 [ 1872 43000]
 [ 1872 43200]
 [ 1872 43400]]


In [129]:
import skimage
skimage.io.imwrite

AttributeError: module 'skimage' has no attribute 'io'

In [130]:
from skimage import io
io.imwri

In [101]:
print(len(sat_master.train_origins))
print(len(sat_master.valid_origins))
print(sat_master.train_origins)
print(sat_master.valid_origins)

70
30
[[22880 17080]
 [28880 26080]
 [22680 16280]
 [14880 14480]
 [29480 22880]
 [18480 24280]
 [28280 27480]
 [14280 16280]
 [17280 19480]
 [25280 18480]
 [18080 16080]
 [28280 16480]
 [23680 30480]
 [13080 28280]
 [27280 28080]
 [21480 23880]
 [15080 19080]
 [19880 30480]
 [15480 23480]
 [21680 26480]
 [15680 29880]
 [18680 23680]
 [29080 25280]
 [17280 23480]
 [30080 22080]
 [19680 22280]
 [21680 14880]
 [21480 16480]
 [24480 26680]
 [21080 27480]
 [22880 26480]
 [30080 21080]
 [24480 15080]
 [16080 21480]
 [27480 24880]
 [29280 18080]
 [23280 14680]
 [20880 29080]
 [16080 15880]
 [29480 19480]
 [22880 18080]
 [28080 26680]
 [28080 27680]
 [27680 16280]
 [25280 22080]
 [23280 25080]
 [29280 19480]
 [18680 29680]
 [27480 29480]
 [13480 28680]
 [13080 19280]
 [30480 25280]
 [26080 19480]
 [16680 26880]
 [19280 13880]
 [24080 21880]
 [17080 17480]
 [20280 20480]
 [26680 19280]
 [14480 15680]
 [19880 28480]
 [15480 23080]
 [27280 29280]
 [14480 17880]
 [22480 28480]
 [13480 29680]
 [17

In [23]:
sat_master.image_save_format.format(1, 1000)

'image_00001_01000'

In [2]:
str(2.)

'2.0'

In [8]:
'{}{}'.format(10, 11)

'1011'

In [25]:
np.random.choice(np.array([[1,2], [3,4], [5,6], [7,8]]), 2)

ValueError: a must be 1-dimensional

In [30]:
np.random.choice(np.arange(10), size=11, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

if 3 not 4:

In [68]:
if not 3==4:
    print('hello')

hello


In [207]:
from scipy.misc import imsave

In [209]:
array =  np.random.rand(10,10,3)
print(array)

[[[0.26332711 0.66190859 0.07043649]
  [0.32917309 0.65722762 0.16594099]
  [0.17846619 0.53931184 0.56056426]
  [0.73929161 0.13087569 0.97056825]
  [0.2698285  0.63516314 0.721763  ]
  [0.2346232  0.12130158 0.15172742]
  [0.07405886 0.37517614 0.91004171]
  [0.67547203 0.41909389 0.27853356]
  [0.80026012 0.75356195 0.36462072]
  [0.88057628 0.62056368 0.72934583]]

 [[0.31847792 0.95215913 0.19467619]
  [0.8095769  0.66098888 0.27185189]
  [0.82525826 0.59029096 0.24061786]
  [0.29975985 0.01743415 0.62978649]
  [0.40630237 0.88849141 0.63081059]
  [0.25547178 0.62573004 0.17140428]
  [0.82331678 0.27913784 0.52816668]
  [0.73372607 0.13267115 0.00236156]
  [0.05504476 0.38132924 0.11194501]
  [0.11850081 0.04543366 0.45011469]]

 [[0.71099998 0.56804693 0.16221707]
  [0.63373458 0.44959168 0.13696522]
  [0.26439769 0.46528353 0.65257131]
  [0.31710776 0.38997358 0.34873296]
  [0.17549995 0.3925157  0.97427481]
  [0.04467492 0.91950185 0.75285561]
  [0.08221637 0.69617578 0.4472411