In [50]:
%load_ext autoreload
%autoreload
%matplotlib inline
# import rasterio
import sys
import numpy as np
sys.path.insert(0, "..")
import src.models.predict_classes

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
tif_path = '../data/raw/athens_satellite.tif'
rel_path = '../data/processed/athens'
sat_master = src.models.predict_classes.SatelliteTif(tif_path, rel_path,
                 c_channels=[0, 1, 3], sub_img_w=200, sub_img_h=200,
                 valid_frac = 0.3,
                 r_start=0, r_end=np.inf, c_start=0, c_end=np.inf)

[[13080. 13080.]
 [13080. 13280.]
 [13080. 13480.]
 ...
 [30480. 30080.]
 [30480. 30280.]
 [30480. 30480.]]


In [52]:
sat_master.pred_origins

array([[    0.,     0.],
       [    0.,   200.],
       [    0.,   400.],
       ...,
       [43400., 43000.],
       [43400., 43200.],
       [43400., 43400.]])

In [53]:
sat_master.train_origins

array([[29880, 28280],
       [26280, 25480],
       [20080, 25080],
       [21680, 25280],
       [24480, 28680],
       [17080, 18680],
       [24680, 20880],
       [24080, 27880],
       [28280, 16880],
       [30080, 18280],
       [14080, 26680],
       [16680, 20080],
       [22280, 29080],
       [25680, 27880],
       [30280, 16680],
       [27680, 19080],
       [20480, 18480],
       [15680, 28680],
       [16280, 28880],
       [16280, 29280],
       [17280, 14280],
       [20080, 28680],
       [24480, 20880],
       [18480, 17280],
       [20880, 13080],
       [29280, 26280],
       [28480, 15080],
       [23680, 29680],
       [20280, 25880],
       [25080, 21080],
       [25080, 20680],
       [14080, 24880],
       [21880, 30480],
       [14480, 27880],
       [16880, 29480],
       [21880, 21080],
       [23680, 26880],
       [15280, 25080],
       [27680, 13880],
       [25480, 28280],
       [21080, 29680],
       [19680, 21080],
       [16680, 29480],
       [244